const BlogCategories = [
  { value: 'Economics', label: 'Economics' },
  { value: 'Parenting', label: 'Parenting' },
  { value: 'Career', label: 'Career' },
  { value: 'Political', label: 'Political' },
  { value: 'Finance', label: 'Finance' },
  { value: 'Pets', label: 'Pets' },
  { value: 'Gaming', label: 'Gaming' },
  { value: 'Nature', label: 'Nature' },
  { value: 'DIY', label: 'DIY' },
  { value: 'Celebrity Gossip', label: 'Celebrity Gossip' },
  { value: 'Wine', label: 'Wine' },
  { value: 'Medicine', label: 'Medicine' },
  { value: 'Sports', label: 'Sports' },
  { value: 'Entertainment', label: 'Entertainment' },
  { value: 'Shopping', label: 'Shopping' },
  { value: 'Science', label: 'Science' },
  { value: 'Education', label: 'Education' },
  { value: 'Fitness', label: 'Fitness' },
  { value: 'Business', label: 'Business' },
  { value: 'Lifestyle', label: 'Lifestyle' },
  { value: 'Photography', label: 'Photography' },
  { value: 'Movies', label: 'Movies' },
  { value: 'Food', label: 'Food' },
  { value: 'Music', label: 'Music' },
  { value: 'Fashion', label: 'Fashion' }
];
export default BlogCategories;
